import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#121214',
    paddingHorizontal: 16,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 40,
    height: 80,
    marginBottom: 8,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  tituloCategoria: {
    color: '#a0a0a8',
    fontSize: 13,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    marginBottom: 12,
    marginTop: 16,
    letterSpacing: 0.5,
  },
  itemConfiguracao: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#141415',
    borderWidth: 1,
    borderColor: '#1e1e22',
    borderRadius: 8,
    paddingHorizontal: 16,
    height: 56,
    marginBottom: 12,
  },
  rowItemEsquerda: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  txtTituloConfig: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '500',
  },
  rowItemDireita: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  txtValorConfig: {
    color: '#a0a0a8',
    fontSize: 14,
    marginRight: 8,
  },
  circuloCorDestaque: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#d30046',
  },
  menuInferiorContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#121214',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    height: 70,
    borderTopWidth: 1,
    borderTopColor: '#242021',
    paddingBottom: 10,
  },
  menuItem: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuItemTextoAtivo: {
    color: '#d30046',
    fontSize: 11,
    marginTop: 4,
  },
  menuItemTextoInativo: {
    color: '#a0a0a8',
    fontSize: 11,
    marginTop: 4,
  },
});
