import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#121214',
    paddingHorizontal: 16,
    paddingTop: 40,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    marginRight: 24,
    fontSize: 22,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  buscaContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#141415',
    borderWidth: 1,
    borderColor: '#323238',
    borderRadius: 8,
    paddingHorizontal: 16,
    height: 52,
    marginBottom: 24,
  },
  buscaIcone: {
    marginRight: 10,
  },
  inputBusca: {
    flex: 1,
    color: '#ffffff',
    fontSize: 16,
  },
  btnFiltro: {
    backgroundColor: '#141415',
    borderColor: '#323238',
    borderWidth: 1,
    borderRadius: 6,
    padding: 8,
    marginLeft: 8,
  },
  secaoTitulo: {
    color: '#a0a0a8',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 12,
  },
  tagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 8,
  },
  tagItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#141415',
    borderWidth: 1,
    borderColor: '#323238',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginRight: 8,
    marginBottom: 8,
  },
  tagTexto: {
    color: '#ffffff',
    fontSize: 13,
    marginRight: 6,
  },
  btnLimparTudo: {
    paddingVertical: 6,
    paddingHorizontal: 4,
  },
  txtLimparTudo: {
    color: '#d30046',
    fontSize: 13,
    fontWeight: 'bold',
  },
  cardFilmePesquisa: {
    flexDirection: 'row',
    backgroundColor: 'rgba(0, 0, 0, 0.79)',
    borderWidth: 1,
    borderColor: '#242021',
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    alignItems: 'center',
  },
  capaFilmePesquisa: {
    width: 60,
    height: 85,
    borderRadius: 6,
    backgroundColor: '#141415',
    marginRight: 12,
  },
  infoFilmePesquisa: {
    flex: 1,
  },
  tituloFilmePesquisa: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  detalhesFilmePesquisa: {
    color: '#a0a0a8',
    fontSize: 13,
    marginTop: 4,
  },
  notaContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
  },
  notaFilme: {
    color: '#d30046',
    fontSize: 12,
    fontWeight: 'bold',
  },
  containerSemResultados: {
    alignItems: 'center',
    marginTop: 40,
    paddingHorizontal: 20,
  },
  txtSemResultados: {
    color: '#a0a0a8',
    fontSize: 14,
    textAlign: 'center',
    marginTop: 12,
  },
  blocoDica: {
    backgroundColor: '#141415',
    borderWidth: 1,
    borderColor: '#323238',
    borderRadius: 8,
    padding: 16,
    marginTop: 16,
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  dicaIcone: {
    marginRight: 12,
    marginTop: 2,
  },
  dicaConteudo: {
    flex: 1,
  },
  dicaTitulo: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: 'bold',
  },
  dicaTexto: {
    color: '#a0a0a8',
    fontSize: 13,
    marginTop: 4,
    lineHeight: 18,
  },
  menuInferiorContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#121214',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    height: 70,
    borderTopWidth: 1,
    borderTopColor: '#242021',
    paddingBottom: 10,
  },
  menuItem: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuItemTextoInativo: {
    color: '#a0a0a8',
    fontSize: 11,
    marginTop: 4,
  },
});
