import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#121214',
    paddingHorizontal: 16,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 40,
    height: 80,
    marginBottom: 8,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  subHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    marginTop: 8,
  },
  txtSubHeader: {
    color: '#a0a0a8',
    fontSize: 14,
  },
  cardOpcao: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#141415',
    borderWidth: 1,
    borderColor: '#1e1e22',
    borderRadius: 8,
    paddingHorizontal: 16,
    height: 64,
    marginBottom: 12,
  },
  blocoEsquerda: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  txtTituloOpcao: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '600',
  },
  txtDescricaoOpcao: {
    color: '#a0a0a8',
    fontSize: 12,
    marginTop: 2,
  },
  btnAplicar: {
    backgroundColor: '#d30046',
    borderRadius: 8,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    marginBottom: 12,
  },
  txtBtnAplicar: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  btnCancelar: {
    borderColor: '#d30046',
    borderWidth: 1,
    borderRadius: 8,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
  },
  txtBtnCancelar: {
    color: '#d30046',
    fontSize: 16,
    fontWeight: '600',
  },
  menuInferiorContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#121214',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    height: 70,
    borderTopWidth: 1,
    borderTopColor: '#242021',
    paddingBottom: 10,
  },
  menuItem: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuItemTextoAtivo: {
    color: '#d30046',
    fontSize: 11,
    marginTop: 4,
  },
  menuItemTextoInativo: {
    color: '#a0a0a8',
    fontSize: 11,
    marginTop: 4,
  },
});
