import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#121214',
    paddingHorizontal: 16,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 40,
    height: 80,
    marginBottom: 8,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  cardInfoFilme: {
    flexDirection: 'row',
    backgroundColor: '#141415',
    borderWidth: 1,
    borderColor: '#1e1e22',
    borderRadius: 8,
    padding: 16,
    marginBottom: 24,
  },
  capaFilme: {
    width: 90,
    height: 130,
    borderRadius: 6,
    backgroundColor: '#323238',
  },
  blocoTextoFilme: {
    flex: 1,
    marginLeft: 16,
    justifyContent: 'center',
  },
  txtTituloFilme: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  txtMetadados: {
    color: '#a0a0a8',
    fontSize: 12,
    marginTop: 2,
  },
  rowNotaStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 8,
  },
  notaContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 12,
  },
  txtNota: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '600',
  },
  badgeStatus: {
    backgroundColor: '#ff006f20',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#d30046',
  },
  txtStatus: {
    color: '#d30046',
    fontSize: 11,
    fontWeight: 'bold',
  },
  txtDescricaoFilme: {
    color: '#a0a0a8',
    fontSize: 12,
    lineHeight: 16,
  },
  secaoTitulo: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 16,
  },
  gradeRedes: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  btnRede: {
    width: '23%',
    alignItems: 'center',
    marginBottom: 20,
  },
  circuloIcone: {
    width: 60,
    height: 60,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  txtNomeRede: {
    color: '#a0a0a8',
    fontSize: 12,
    textAlign: 'center',
  },
  btnCancelar: {
    borderColor: '#323238',
    borderWidth: 1,
    borderRadius: 8,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  txtBtnCancelar: {
    color: '#d30046',
    fontSize: 16,
    fontWeight: 'bold',
  },
  menuInferiorContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#121214',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    height: 70,
    borderTopWidth: 1,
    borderTopColor: '#242021',
    paddingBottom: 10,
  },
  menuItem: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuItemTextoAtivo: {
    color: '#d30046',
    fontSize: 11,
    marginTop: 4,
  },
  menuItemTextoInativo: {
    color: '#a0a0a8',
    fontSize: 11,
    marginTop: 4,
  },
});
