import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  body: {
    flex: 1,
    backgroundColor: '#121214',
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 40,
  },
  background: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  backgroundDark: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.69)', 
  },
  title: {
    flexDirection: 'row',
    marginBottom: 2,
    alignItems: 'center',
  },
  image: {
    width: 80,
    height: 80,
    resizeMode: 'contain',
    marginRight: 6,
  },
  textMovie: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#ffffff',
    marginBottom: -25,
  },
  textHub: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#d30046',
    marginBottom: -25,
  },
  descricao: {
    marginBottom: 30,
    alignItems: 'center',
  },
  textDescricao: {
    fontSize: 16,
    color: '#a0a0a8',
    fontWeight: '500',
  },
  container: {
    width: width * 0.87, 
    padding: 24,
    borderRadius: 12,
    backgroundColor: 'rgba(0, 0, 0, 0.79)', 
    borderWidth: 1,
    borderColor: '#242021',
  },
  headerCadastroContainer: {
    alignItems: 'center',
    marginBottom: 24,
    width: '100%',
  },
  headerCadastroTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#ffffff',
    marginBottom: 4,
  },
  textConta: {
    color: '#d30046',
  },
  headerCadastroSubtitle: {
    fontSize: 14,
    color: '#a0a0a8',
    marginBottom: 20,
    fontWeight: '400',
  },
  avatarButton: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  avatarCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#202024',
    borderWidth: 1,
    borderColor: '#323238',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  avatarBadgeCircle: {
    position: 'absolute',
    bottom: 2,
    right: 2,
    backgroundColor: '#d30046', 
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'rgba(0, 0, 0, 0.79)', 
  },
  avatarLabelText: {
    fontSize: 12,
    color: '#a0a0a8',
    fontWeight: '500',
  },
  button: {
    backgroundColor: '#d30046', 
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
    marginBottom: 20,
    shadowColor: '#d3007f',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  textButton: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  linkCadastro: {
    color: '#a0a0a8',
    fontSize: 14,
    textAlign: 'center',
    marginTop: 10,
  },
  linkCriarConta: {
    color: '#d30046',
    fontWeight: 'bold',
  },
  loading: {
    marginVertical: 20,
    alignItems: 'center',
  },
  inputLabel: {
    fontSize: 14,
    color: '#ffffff',
    alignSelf: 'flex-start',
    marginBottom: 6,
    fontWeight: '500',
  },
  inputRowContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#141415e8',
    borderWidth: 1,
    borderColor: '#323238', 
    borderRadius: 8,
    paddingHorizontal: 16,
    height: 52,
    marginBottom: 16,
  },
  inputIcon: {
    marginRight: 10,
  },
  input: {
    flex: 1,
    color: '#ffffff',
    fontSize: 16,
    height: '100%',
  },
});