import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#121214',
    paddingHorizontal: 16,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 40,
    height: 80,
    marginBottom: 8,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  blocoUsuario: {
    alignItems: 'center',
    marginBottom: 28,
    marginTop: 8,
  },
  containerAvatar: {
    width: 90,
    height: 90,
    marginBottom: 16,
    position: 'relative',
  },
  avatar: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: '#323238',
  },
  btnCameraAvatar: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: '#575757',
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#121214',
  },
  txtNome: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: 'bold',
  },
  txtEmail: {
    color: '#a0a0a8',
    fontSize: 14,
    marginTop: 4,
  },
  rowMembro: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  txtMembro: {
    color: '#a0a0a8',
    fontSize: 12,
  },
  gridEstatisticas: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 28,
  },
  cardEstatistica: {
    width: '23%',
    backgroundColor: '#141415',
    borderWidth: 1,
    borderColor: '#1e1e22',
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
  },
  txtLabelEstatistica: {
    color: '#a0a0a8',
    fontSize: 10,
    textAlign: 'center',
    marginTop: 6,
    marginBottom: 4,
  },
  txtValorEstatistica: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  listaOpcoes: {
    marginBottom: 28,
  },
  btnOpcao: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#141415',
    borderWidth: 1,
    borderColor: '#1e1e22',
    borderRadius: 8,
    paddingHorizontal: 16,
    height: 56,
    marginBottom: 12,
  },
  rowOpcaoEsquerda: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  txtTituloOpcao: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '500',
  },
  btnSair: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#E51C4430',
    borderWidth: 1,
    borderRadius: 8,
    height: 52,
    backgroundColor: '#E51C4410',
  },
  txtBtnSair: {
    color: '#E51C44',
    fontSize: 16,
    fontWeight: 'bold',
  },
  menuInferiorContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#121214',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    height: 70,
    borderTopWidth: 1,
    borderTopColor: '#242021',
    paddingBottom: 10,
  },
  menuItem: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuItemTextoAtivo: {
    color: '#d30046',
    fontSize: 11,
    marginTop: 4,
  },
  menuItemTextoInativo: {
    color: '#a0a0a8',
    fontSize: 11,
    marginTop: 4,
  },
});
