import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 16,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 40,
    marginBottom: 16,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  blocoTopo: {
    flexDirection: 'row',
    marginVertical: 16,
  },
  capaFilme: {
    width: 130,
    height: 190,
    borderRadius: 8,
    backgroundColor: '#141415',
  },
  infoPrincipais: {
    flex: 1,
    marginLeft: 16,
  },
  txtTituloFilme: {
    color: '#ffffff',
    fontSize: 22,
    fontWeight: 'bold',
  },
  txtMetadados: {
    color: '#a0a0a8',
    fontSize: 14,
    marginTop: 4,
  },
  rowNotaStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 8,
  },
  notaContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 12,
  },
  txtNota: {
    color: '#ffffff',
    fontWeight: 'bold',
    fontSize: 15,
  },
  badgeStatus: {
    backgroundColor: '#d30046',
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 12,
  },
  txtStatus: {
    color: '#000000',
    fontSize: 11,
    fontWeight: 'bold',
  },
  txtLabelInfo: {
    color: '#a0a0a8',
    fontSize: 12,
    marginTop: 6,
  },
  txtValorInfo: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '500',
  },
  secaoTitulo: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
    marginTop: 22,
    marginBottom: 8,
  },
  txtDescricao: {
    color: '#a0a0a8',
    fontSize: 14,
    lineHeight: 20,
  },
  blocoAvaliacao: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#141415',
    borderWidth: 1,
    borderColor: '#242021',
    padding: 16,
    borderRadius: 8,
  },
  rowEstrelas: {
    flexDirection: 'row',
  },
  txtAvaliacaoNumero: {
    color: '#d30046',
    fontSize: 18,
    fontWeight: 'bold',
  },
  btnTrailer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#141415',
    borderWidth: 1,
    borderColor: '#242021',
    padding: 16,
    borderRadius: 8,
  },
  rowTrailerEsquerda: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  txtTrailer: {
    color: '#a0a0a8',
    fontSize: 14,
    fontWeight: '500',
  },
  gradeAcoes: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 24,
  },
  cardAcao: {
    flex: 1,
    backgroundColor: '#141415',
    borderWidth: 1,
    borderColor: '#242021',
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
    marginHorizontal: 4,
  },
  txtCardAcao: {
    color: '#a0a0a8',
    fontSize: 11,
    marginTop: 6,
    fontWeight: '500',
  },
  menuInferiorContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#121214',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    height: 70,
    borderTopWidth: 1,
    borderTopColor: '#242021',
    paddingBottom: 10,
  },
  menuItem: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuItemTextoAtivo: {
    color: '#d30046',
    fontSize: 11,
    marginTop: 4,
    fontWeight: 'bold',
  },
  menuItemTextoInativo: {
    color: '#a0a0a8',
    fontSize: 11,
    marginTop: 4,
  },
});