import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#121214',
    paddingHorizontal: 16,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 40,
    marginBottom: 24,
    height: 80,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  txtLimpar: {
    color: '#d30046',
    fontSize: 16,
    fontWeight: '600',
  },
  labelSecao: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 12,
  },
  dropdownContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#141415',
    borderWidth: 1,
    borderColor: '#323238',
    borderRadius: 8,
    paddingHorizontal: 16,
    height: 52,
    marginBottom: 24,
  },
  btnStatus: {
    backgroundColor: '#141415',
    borderWidth: 1,
    borderColor: '#323238',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    marginRight: 8,
  },
  btnStatusAtivo: {
    backgroundColor: '#d30046',
    borderColor: '#d30046',
  },
  txtStatus: {
    color: '#a0a0a8',
    fontSize: 14,
    fontWeight: '500',
  },
  txtStatusAtivo: {
    color: '#ffffff',
    fontWeight: 'bold',
  },
  rowCampos: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  inputRowContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#141415',
    borderWidth: 1,
    borderColor: '#323238',
    borderRadius: 8,
    paddingHorizontal: 16,
    height: 52,
  },
  input: {
    flex: 1,
    color: '#ffffff',
    fontSize: 16,
  },
  rowEstrelasContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  rowSwitch: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  btnAplicar: {
    backgroundColor: '#d30046',
    borderRadius: 8,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginBottom: 12,
  },
  txtBtnAplicar: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  btnCancelar: {
    borderColor: '#d30046',
    borderWidth: 1,
    borderRadius: 8,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
  },
  txtBtnCancelar: {
    color: '#d30046',
    fontSize: 16,
    fontWeight: '600',
  },
  menuInferiorContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#121214',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    height: 70,
    borderTopWidth: 1,
    borderTopColor: '#242021',
    paddingBottom: 10,
  },
  menuItem: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuItemTextoInativo: {
    color: '#a0a0a8',
    fontSize: 11,
    marginTop: 4,
  },
});
