import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 16,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 40,
    marginBottom: 10,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  uploadContainer: {
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#323238',
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    borderRadius: 8,
    padding: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 16,
  },
  textUploadDescricao: {
    color: '#a0a0a8',
    fontSize: 13,
    marginBottom: 12,
  },
  uploadBotoesRow: {
    flexDirection: 'row',
  },
  btnUploadOpcao: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#323238',
    borderRadius: 6,
    paddingVertical: 6,
    paddingHorizontal: 12,
    marginHorizontal: 6,
    backgroundColor: '#141415',
  },
  txtUploadOpcao: {
    color: '#ffffff',
    fontSize: 13,
  },
  inputLabel: {
    fontSize: 14,
    color: '#ffffff',
    alignSelf: 'flex-start',
    marginBottom: 6,
    marginTop: 12,
    fontWeight: '500',
  },
  inputRowContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#141415',
    borderWidth: 1,
    borderColor: '#323238', 
    borderRadius: 8,
    paddingHorizontal: 16,
    height: 52,
  },
  input: {
    flex: 1,
    color: '#ffffff',
    fontSize: 16,
    height: '100%',
  },
  rowDupla: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  estrelasRow: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 52,
  },
  buttonSalvar: {
    backgroundColor: '#d30046', // Cor de destaque padrão do seu projeto
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 24,
    shadowColor: '#d3007f',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  textButtonSalvar: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  buttonCancelar: {
    borderWidth: 1,
    borderColor: '#323238',
    backgroundColor: 'transparent',
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
  },
  textButtonCancelar: {
    color: '#a0a0a8',
    fontSize: 16,
    fontWeight: '500',
  },
});