import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#121214',
    paddingHorizontal: 16,
    paddingTop: 40,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  headerTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  textMovie: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  textHub: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#d30046',
  },
  saudacaoContainer: {
    marginBottom: 20,
  },
  txtOla: {
    color: '#ffffff',
    fontSize: 24,
    fontWeight: 'bold',
  },
  txtSubtitulo: {
    color: '#a0a0a8',
    fontSize: 14,
    marginTop: 4,
    fontWeight: '500',
  },
  buscaContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#141415',
    borderWidth: 1,
    borderColor: '#323238',
    borderRadius: 8,
    paddingHorizontal: 16,
    height: 52,
    marginBottom: 24,
  },
  buscaIcone: {
    marginRight: 10,
  },
  inputBusca: {
    flex: 1,
    color: '#ffffff',
    fontSize: 16,
  },
  btnMais: {
    backgroundColor: '#d30046',
    borderRadius: 6,
    padding: 6,
    marginLeft: 8,
    shadowColor: '#d3007f',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 3,
  },
  secaoHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 24,
  },
  secaoTitulo: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 12,
  },
  txtVerTodos: {
    color: '#d30046',
    fontSize: 14,
    fontWeight: 'bold',
  },
  resumoContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  cardResumo: {
    backgroundColor: 'rgba(0, 0, 0, 0.79)',
    borderWidth: 1,
    borderColor: '#242021',
    flex: 1,
    marginHorizontal: 4,
    borderRadius: 8,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardResumoLabel: {
    color: '#a0a0a8',
    fontSize: 10,
    textAlign: 'center',
    marginTop: 6,
    height: 28,
  },
  cardResumoValor: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
    marginTop: 4,
  },
  listaFilmes: {
    flexDirection: 'row',
  },
  cardFilme: {
    width: 110,
    marginRight: 12,
  },
  capaFilme: {
    width: 110,
    height: 160,
    borderRadius: 8,
    backgroundColor: '#141415',
    borderWidth: 1,
    borderColor: '#242021',
  },
  tituloFilme: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
    marginTop: 6,
  },
  anoFilme: {
    color: '#a0a0a8',
    fontSize: 12,
    marginTop: 2,
  },
  notaContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  notaFilme: {
    color: '#d30046',
    fontSize: 12,
    fontWeight: 'bold',
  },
  menuInferiorContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#121214',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    height: 70,
    borderTopWidth: 1,
    borderTopColor: '#242021',
    paddingBottom: 10,
  },
  menuItem: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuItemTextoAtivo: {
    color: '#d30046',
    fontSize: 11,
    marginTop: 4,
    fontWeight: 'bold',
  },
  menuItemTextoInativo: {
    color: '#a0a0a8',
    fontSize: 11,
    marginTop: 4,
  },
});