import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 16,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 40,
    marginBottom: 10,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  blocoImagemEdicao: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 12,
  },
  previewCapa: {
    width: 85,
    height: 120,
    borderRadius: 6,
    backgroundColor: '#141415',
  },
  botoesImagemColuna: {
    flex: 1,
    marginLeft: 16,
    justifyContent: 'center',
  },
  btnUploadOpcao: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#d30046',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 16,
    marginBottom: 8,
    backgroundColor: '#141415',
  },
  txtUploadOpcao: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '500',
  },
  inputLabel: {
    fontSize: 14,
    color: '#ffffff',
    alignSelf: 'flex-start',
    marginBottom: 6,
    marginTop: 12,
    fontWeight: '500',
  },
  inputRowContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#141415',
    borderWidth: 1,
    borderColor: '#323238', 
    borderRadius: 8,
    paddingHorizontal: 16,
    height: 52,
    marginBottom: 4,
  },
  input: {
    flex: 1,
    color: '#ffffff',
    fontSize: 16,
    height: '100%',
  },
  rowDupla: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  estrelasRow: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 52,
  },
  txtNotaTexto: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: 'bold',
    marginLeft: 6,
  },
  buttonSalvar: {
    backgroundColor: '#d30046', // Sua cor vinho oficial
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 24,
    shadowColor: '#d3007f',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  textButtonSalvar: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  buttonCancelar: {
    borderWidth: 1,
    borderColor: '#d30046',
    backgroundColor: 'transparent',
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
  },
  textButtonCancelar: {
    color: '#e2004b',
    fontSize: 16,
    fontWeight: '500',
  },
});